### ISSUE TITLE
Script does not seem to work under windows 10

### ISSUE THREAD

**Issue by frimdo** [rdpoor/rigol-grab#5]
I am using Windows10 and Rigol DS1054Z connected using USB. The scope appeared in device manager with "no driver installed" message. 
I installed script by following the setup step by step, then I tried to run the script:
```
\rigol-grab>python rigol_grab.py --auto_open -v
Traceback (most recent call last):
  File "rigol_grab.py", line 66, in <module>
    grabber.grab(filename=opts.filename, auto_open=opts.auto_open)
  File "rigol_grab.py", line 23, in grab
    buf = self.rigol().query_binary_values(':DISP:DATA? ON,0,PNG', datatype='B')
  File "rigol_grab.py", line 32, in rigol
    self._rigol = self._resource_manager.open_resource(name)
  File "C:\SPB_Data\.virtualenvs\rigol-grab-Tom2Ahzx\lib\site-packages\pyvisa\highlevel.py", line 1724, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\SPB_Data\.virtualenvs\rigol-grab-Tom2Ahzx\lib\site-packages\pyvisa\resources\resource.py", line 209, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "C:\SPB_Data\.virtualenvs\rigol-grab-Tom2Ahzx\lib\site-packages\pyvisa\highlevel.py", line 1681, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\SPB_Data\.virtualenvs\rigol-grab-Tom2Ahzx\lib\site-packages\pyvisa-py\highlevel.py", line 194, in open
    sess = cls(session, resource_name, parsed, open_timeout)
  File "C:\SPB_Data\.virtualenvs\rigol-grab-Tom2Ahzx\lib\site-packages\pyvisa-py\sessions.py", line 213, in __init__
    self.after_parsing()
  File "C:\SPB_Data\.virtualenvs\rigol-grab-Tom2Ahzx\lib\site-packages\pyvisa-py\usb.py", line 201, in after_parsing
    self.parsed.serial_number)
  File "C:\SPB_Data\.virtualenvs\rigol-grab-Tom2Ahzx\lib\site-packages\pyvisa-py\protocols\usbtmc.py", line 256, in __init__
    super(USBTMC, self).__init__(vendor, product, serial_number, **kwargs)
  File "C:\SPB_Data\.virtualenvs\rigol-grab-Tom2Ahzx\lib\site-packages\pyvisa-py\protocols\usbtmc.py", line 169, in __init__
    raise ValueError('No device found.')
ValueError: No device found.
```

Any ideas? I am willing to test under windows further.

**Comment by rdpoor** [comment]
@frimdo : I take delivery of a Windows box tomorrow (!) so I'll be able to dig into this more.  Thanks for the heads-up!

**Comment by frimdo** [comment]
Hi, any news regarding this issue?

**Comment by rdpoor** [comment]
@frimdo Yes (and pardon the long delay).  It now runs nicely on my Windows 10 system (even better than on my mac...).  Please pull the latest and let me know if you have any problems.

**Comment by frimdo** [comment]
Hi - the script runs, but seems not to be able to find the device. Any ideas?

![image](https://user-images.githubusercontent.com/10960486/66634749-03440f00-ec0e-11e9-9caf-1e214aae2588.png)
 The same output is for cmd with admin rights.

**Comment by rdpoor** [comment]
Rigol has a device drivers here:

    http://int.rigol.com/Support/SoftDownload/1

You'll want to install the the DS1000Z IVI Driver:

    http://int.rigol.com/File/ProductSoftWare/20150909/DS1000Z%20IVI%20Driver.rar

Let me know if that works for you!

**Comment by rdpoor** [comment]
FWIW, here's what you should see once the driver is installed.  To get to this screen:

Open Device Manager => 
USB Test and Measurement Devices => 
USB Test and Measurement Device (IVI) => 
USB Test and Measurement Device (IVI) Properties =>
Details tab =>
Property: Hardware Ids
<img width="403" alt="Screen Shot 2019-10-11 at 08 19 18" src="https://user-images.githubusercontent.com/1796161/66663842-4a2b0800-ec00-11e9-91de-1cd8c74e5aad.png">

**Comment by frimdo** [comment]
Hi, I installed the [IVI Compliance Package 16.0.1](http://www.ni.com/cs-cz/support/downloads/drivers/download.ivi-compliance-package.html#305841) and [DS1000Z IVI Driver](http://int.rigol.com/File/ProductSoftWare/20150909/DS1000Z%20IVI%20Driver.rar), but nothing changed. Am I missing something?


![image](https://user-images.githubusercontent.com/10960486/67280767-2d2ee880-f4ce-11e9-9320-42b45f9bda44.png)
